# This is a basic workflow to help you get started with Actions

name: This is a CICD execution process for a video streamwhich will do integration and then deploy the app in mentioned specific environment

